# Generated by Django 3.1.7 on 2021-03-08 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ing_have',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ing_text',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ingredients.foodtype'),
            preserve_default=False,
        ),
    ]
