# Generated by Django 3.1.7 on 2021-03-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20210307_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='type',
            field=models.CharField(default='Meat', max_length=200),
        ),
    ]
