# Generated by Django 3.1.7 on 2021-03-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20210307_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='pub_date',
        ),
    ]
