# Generated by Django 3.1.7 on 2021-03-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_remove_foodtype_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(choices=[('a', ''), ('b', 'Cup'), ('c', 'Oz'), ('d', 'Lb')], max_length=1),
        ),
    ]
