# Generated by Django 3.1.7 on 2021-03-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_auto_20210307_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(choices=[('a', ''), ('b', 'Cup'), ('c', 'Oz'), ('d', 'Lb')], default='', max_length=1),
        ),
    ]
