# Generated by Django 3.1.7 on 2021-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20210307_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
