# Generated by Django 3.1.7 on 2021-03-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_auto_20210307_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='type',
            field=models.CharField(default='', help_text='Think different sections of the grocery store, like meat, bread, or vegetables', max_length=200),
        ),
    ]
