# Generated by Django 3.1.7 on 2021-03-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_auto_20210307_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='metric',
            field=models.ForeignKey(default='lb', on_delete=django.db.models.deletion.CASCADE, to='ingredients.metric'),
            preserve_default=False,
        ),
    ]
