# Generated by Django 3.1.7 on 2021-03-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_ingredient_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='metric',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ingredients.metric'),
        ),
    ]
