# Generated by Django 3.1.7 on 2021-03-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_auto_20210307_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='metric',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
