# Generated by Django 3.1.7 on 2021-03-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_auto_20210307_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
    ]
